version: '3'

services:

  my_api_service:
    build:
      context: .
      dockerfile: api.dockerfile
    container_name: my_api
    restart: always
    ports:
      - "8091:8090"
    deploy:
      mode: replicated
      replicas: 1
    environment:
      DB_ADDR: "postgresql://postgres_user:postgres_password@my_postgres:5432/postgres_db_name?sslmode=disable"
      API_URL: "0.0.0.0:8090"
    depends_on:
      - my_postgres
    volumes:  
      - /bin:/bin 
    networks:
      - my_network

  my_web_service:
    build:
      context: .
      dockerfile: web.dockerfile
    container_name: my_web
    restart: always
    ports:
      - "8093:8092"
    deploy:
      mode: replicated
      replicas: 1
    environment: 
      DATABASE_HOST: "postgres"
      DATABASE_PORT: "5432"
    depends_on:
      - postgres
    volumes:
      - ./public/:/app/public/
      - ./.env:/app/.env:ro 
    networks:
      - my_network

#  start Postgres, and ensure that data is stored to a mounted volume
  my_postgres:
    image: 'postgres:13.4'
    ports:
      - "5470:5432"
    restart: always
    environment:
      POSTGRES_USER: postgres_user
      POSTGRES_PASSWORD: postgres_password
      POSTGRES_DB: postgres_db_name
    volumes:
      - ./db-data/postgres/:/var/lib/postgresql/data/
    networks:
      - my_network

  #  start Redis, and ensure that data is stored to a mounted volume
  my_redis:
    image: 'redis:alpine'
    ports:
      - "6336:6379"
    restart: always
    volumes:
      - ./db-data/redis/:/data
    networks:
      - my_network

  #  start sftp webdav, and admin interface; ensure that data is stored to a mounted volume
  # sftp:
  #   image: 'drakkan/sftpgo:latest'
  #   ports:
  #     - "8030:8080"
  #     - "2030:2022"
  #     - "10030:10080"
  #   restart: always
  #   environment:
  #     SFTPGO_WEBDAVD__BINDINGS__0__PORT: 10080
  #   volumes:
  #     - ./db-data/sftp/:/mnt/data/
  #     - ./db-data/home/:/var/lib/sftpgo

  #  start minio, and ensure that data is stored to a mounted volume
  my_minio:
    image: 'quay.io/minio/minio'
    command: server /mnt/data --console-address ":9001"
    ports:
      - "8008:9000"
      - "9009:9001"
    restart: always
    environment:
      MINIO_ROOT_USER: root
      MINIO_ROOT_PASSWORD: password
    volumes:
      - ./db-data/minio/:/mnt/data/
    networks:
      - socle_network

  #  start MariaDB, and ensure that data is stored to a mounted volume
  # mariadb:
  #   image: 'mariadb:10.6'
  #   ports:
  #     - "3306:3306"
  #   restart: always
  #   environment:
  #     MYSQL_ROOT_PASSWORD: password
  #     MYSQL_DATABASE: celeritas
  #     MYSQL_USER: mariadb
  #     MYSQL_PASSWORD: password

  #   volumes:
  #     - ./db-data/mariadb/:/var/lib/mysql


networks:
  my_network:
    driver: bridge