Project dgdn_doc_checking {
  database_type: 'PostgreSQL'
  Note: '''
    # DGDN DOC-CHECKING DATABASE
  '''
}
 
Table "import_file" as IF {
  "id" bigserial [pk]   
  "document_type"  varchar(50) [not null]  
  "file_name"  varchar(255) [not null]   
  "original_name"  varchar(255) [not null]    
  "status"  varchar(50) [not null]   
  "size" int  [not null]   
  "created_at" timestamptz [not null, default: `now()`]  
}

Table "import_logs" as IL {
  "id" bigserial [pk]   
  "document_type"  varchar(50) [not null]   
  "error_description"  varchar(255) [not null] 
  "data" jsonb   [not null]  
  "file_id" int [not null] 
  "created_at" timestamptz [not null, default: `now()`]  
}

Table "national_identity_card" as ID_CARD {
  "id" bigserial [pk]  
  "application_id" varchar(50)  [default: null, note: 'Application ID']
  "application_date" varchar(50)  [default: null, note: 'Application date'] 
  "application_reason" varchar(100)  [default: null, note: ''] 
  
  "document_number" varchar(50) [not null, note: 'Document ID. It changes for every new application of a person']
  "expiring_on" varchar(50) [not null] 
  "issued_on" varchar(50) [not null] 
  "issued_in" varchar(150) [default: null] 

  "person_id" varchar(50) [not null, note: '']
  "national_id_number" varchar(50) [not null, note: 'National Identification Number. Unique Citizen Identifier which can not be changes']
  "firstname" varchar(255) [not null]  
  "lastname" varchar(150) [not null]   
  "original_name" varchar(150) [default: null]  
  "spouse_name" varchar(150) [default: null]  
  "gender"  varchar(10) [not null]
  "birthdate" varchar(50) [not null] 
  "birthplace" varchar(150) [default: null] 
  "birth_country" varchar(150) [default: null]  
  "prefecture" varchar(100) [default: null]  
  "birth_certificate_number" varchar(50) [default: null]
  "birth_certificate_issued_on" varchar(50) [default: null]
  "birth_certificate_issued_in" varchar(150) [default: null]
  "nationality_certificate_number" varchar(50) [default: null]
  "nationality_certificate_issued_on" varchar(50) [default: null] 
  "profession" varchar(150) [default: null]
  "marital_status" varchar(50) [default: null]  
  "address" varchar(255) [default: null]  
  "other_address" varchar(255) [default: null]   
  "height" int [default: null]  
  "particular_signs" varchar(255) [default: null]
  "hair_color" varchar(50) [default: null] 
  "blood_group" varchar(50) [default: null] 
  "mother_firstname" varchar(150) [default: null]
  "mother_lastname" varchar(150) [default: null]
  "father_firstname" varchar(150) [default: null]
  "father_lastname" varchar(150) [default: null] 
  "poc_firstname" varchar(150) [default: null, note: 'Name of contact person']
  "poc_lastname" varchar(150) [default: null] 
  "poc_address" varchar(255) [default: null]
  "poc_phone" varchar(50) [default: null] 
  "photo" varchar(50) [not null]     
  "created_at" timestamptz [not null, default: `now()`]
  "updated_at" timestamptz [not null, default: `now()`] 
  
  Indexes {
    document_number
    national_id_number
  }
}  


Table "passport" as P {
  "id" bigserial [pk]  
  "application_id" varchar(50)  [default: null, note: 'Application ID']
  "application_date" varchar(50)  [default: null, note: 'Application date']
  "application_reason" varchar(100)  [default: null, note: ''] 

  "document_type" varchar(50) [default: null, note: 'Passport Type'] 
  "document_number" varchar(50) [not null, note: 'Document ID. It changes for every new application of a person'] 
  "expiring_on" varchar(50) [not null] 
  "issued_on" varchar(50) [not null] 
  "issued_in" varchar(150) [default: null] 

  "hncr_id_number" varchar(50) [default: null, note: '']  
  "hncr_issued_on" varchar(50) [default: null] 

  "cnar_id_number" varchar(50) [default: null, note: '']  
  "cnar_issued_on" varchar(50) [default: null] 

  "person_id" varchar(50) [not null, note: '']
  "national_id_number" varchar(50) [default: null, note: 'National Identification Number. Unique Citizen Identifier which can not be changes']
  "firstname" varchar(255) [not null]  
  "lastname" varchar(150) [not null]   
  "original_name" varchar(150) [default: null]  
  "spouse_name" varchar(150) [default: null]  
  "gender"  varchar(10) [not null]
  "birthdate" varchar(50) [not null] 
  "birthplace" varchar(150) [default: null] 
  "birth_country" varchar(150) [default: null]  
  "prefecture" varchar(100) [default: null]  
  "birth_certificate_number" varchar(50) [default: null]
  "birth_certificate_issued_on" varchar(50) [default: null]
  "birth_certificate_issued_in" varchar(150) [default: null]
  "nationality_certificate_number" varchar(50) [default: null]
  "nationality_certificate_issued_on" varchar(50) [default: null] 
  "profession" varchar(150) [default: null]
  "marital_status" varchar(50) [default: null]  
  "address" varchar(255) [default: null]  
  "other_address" varchar(255) [default: null]   
  "height" int [default: null]  
  "particular_signs" varchar(255) [default: null]
  "hair_color" varchar(50) [default: null] 
  "face_shape" varchar(50) [default: null] 
  "blood_group" varchar(50) [default: null] 
  "mother_firstname" varchar(150) [default: null]
  "mother_lastname" varchar(150) [default: null]
  "mother_nationality" varchar(150) [default: null]
  "father_firstname" varchar(150) [default: null]
  "father_lastname" varchar(150) [default: null] 
  "father_nationality" varchar(150) [default: null] 
  "poc_firstname" varchar(150) [default: null, note: 'Name of contact person']
  "poc_lastname" varchar(150) [default: null] 
  "poc_address" varchar(255) [default: null]
  "poc_phone" varchar(50) [default: null] 
  "photo" varchar(50) [not null]     
  "created_at" timestamptz [not null, default: `now()`]
  "updated_at" timestamptz [not null, default: `now()`] 

  Indexes {  
    document_number  
  }
}  



Table "residence_permit" as RP {
  "id" bigserial [pk]
  "application_id" varchar(50)  [default: null, note: 'Application ID']
  "application_date" varchar(50)  [default: null, note: 'Application date']
  "application_reason" varchar(100)  [default: null, note: ''] 

  "document_type" varchar(50) [default: null, note: 'Residence permit Type'] 
  "document_number" varchar(50) [not null, note: 'Document ID. It changes for every new application of a person'] 
  "expiring_on" varchar(50) [not null] 
  "issued_on" varchar(50) [not null] 
  "issued_in" varchar(150) [default: null] 

  "passport_number" varchar(50) [not null, note: '']
  "passport_issued_on" varchar(50) [default: null, note: '']
  "passport_expiring_on" varchar(50) [default: null, note: ''] 

  "visa_number" varchar(50) [default: null, note: '']
  "visa_issued_on" varchar(50) [default: null, note: '']
  "visa_expiring_on" varchar(50) [default: null, note: ''] 
  "visa_type" varchar(50) [default: null, note: ''] 

  "person_id" varchar(50) [not null, note: ''] 
  "firstname" varchar(255) [default: null]  
  "lastname" varchar(150) [default: null]   
  "original_name" varchar(150) [default: null]   
  "gender"  varchar(10) [not null]
  "birthdate" varchar(50) [not null] 
  "birthplace" varchar(150) [default: null] 
  "birth_country" varchar(150) [default: null]  
  "nationality" varchar(150) [not null]   
  "birth_certificate_number" varchar(50) [default: null]
  "birth_certificate_issued_on" varchar(50) [default: null] 
  "nationality_certificate_number" varchar(50) [default: null]
  "nationality_certificate_issued_on" varchar(50) [default: null] 
  "profession" varchar(150) [default: null]
  "religion" varchar(150) [default: null]
  "marital_status" varchar(50) [default: null]  
  "address" varchar(255) [default: null]  
  "other_address" varchar(255) [default: null]   
  "height" int [default: null]  
  "particular_signs" varchar(255) [default: null]
  "hair_color" varchar(50) [default: null] 
  "blood_group" varchar(50) [default: null] 
  "mother_maiden_firstname" varchar(150) [default: null]
  "mother_firstname" varchar(150) [default: null]
  "mother_lastname" varchar(150) [default: null] 
  "father_firstname" varchar(150) [default: null]
  "father_lastname" varchar(150) [default: null]  
  "poc_firstname" varchar(150) [default: null, note: 'Name of contact person']
  "poc_lastname" varchar(150) [default: null] 
  "poc_address" varchar(255) [default: null]
  "poc_phone" varchar(50) [default: null] 
  "bank_account_number" varchar(50) [default: null, note: '']
  "bank_name" varchar(50) [default: null, note: '']
  "tax_id_number" varchar(50) [default: null, note: 'Tax Identification Number / Quitus fiscal']
  "criminal_record_number" varchar(50) [default: null, note: 'Criminal record  Number / Casier judiciare']
  "photo" varchar(50) [not null]     
  "created_at" timestamptz [not null, default: `now()`]
  "updated_at" timestamptz [not null, default: `now()`] 


  Indexes {  
    document_number
  } 
}  
 
 
Table "driving_licence" as DL {
  "id" bigserial [pk]  
  "application_id" varchar(50)  [default: null, note: 'Application ID']
  "application_date" varchar(50)  [default: null, note: 'Application date']
  "application_reason" varchar(100)  [default: null, note: ''] 
  
  "document_number" varchar(50) [not null, note: 'Document ID. It changes for every new application of a person']
  "expiring_on" varchar(50) [not null] 
  "issued_on" varchar(50) [not null] 
  "issued_in" varchar(150) [default: null] 

  "person_id" varchar(50) [not null, note: '']
  "national_id_number" varchar(50) [default: null, note: 'National Identification Number. Unique Citizen Identifier which can not be changes']
  "firstname" varchar(255) [default: null]  
  "lastname" varchar(150) [default: null]   
  "original_name" varchar(150) [default: null]  
  "spouse_name" varchar(150) [default: null]  
  "gender"  varchar(10) [not null]
  "birthdate" varchar(50) [not null] 
  "birthplace" varchar(150) [default: null] 
  "birth_country" varchar(150) [default: null]   
  "nationality" varchar(150) [not null]   
  "birth_certificate_number" varchar(50) [default: null]
  "birth_certificate_issued_on" varchar(50) [default: null]
  "birth_certificate_issued_in" varchar(150) [default: null] 
  "nationality_certificate_number" varchar(50) [default: null]
  "nationality_certificate_issued_on" varchar(50) [default: null] 
  "profession" varchar(150) [default: null]
  "marital_status" varchar(50) [default: null]  
  "address" varchar(255) [default: null]  
  "other_address" varchar(255) [default: null]   
  "height" int [default: null]  
  "particular_signs" varchar(255) [default: null]
  "hair_color" varchar(50) [default: null] 
  "blood_group" varchar(50) [default: null] 
  "mother_firstname" varchar(150) [default: null]
  "mother_lastname" varchar(150) [default: null]
  "father_firstname" varchar(150) [default: null]
  "father_lastname" varchar(150) [default: null] 
  "poc_firstname" varchar(150) [default: null, note: 'Name of contact person']
  "poc_lastname" varchar(150) [default: null] 
  "poc_address" varchar(255) [default: null]
  "poc_phone" varchar(50) [default: null] 
  "examination_center" varchar(150) [default: null] 
  "examination_number" varchar(50) [default: null] 
  "vehicle_category" varchar(50) [default: null] 
  "photo" varchar(50) [not null]     
  "created_at" timestamptz [not null, default: `now()`]
  "updated_at" timestamptz [not null, default: `now()`] 

  Indexes {  
    document_number
  }
} 


Table "vehicle_registration" as VR {
  "id" bigserial [pk]  
  "application_id" varchar(100)  [default: null, note: 'Application ID']
  "application_date" varchar(100)  [default: null, note: 'Application date']
  "application_reason" varchar(250)  [default: null, note: ''] 
  
  "document_number" varchar(100) [default: null, note: 'Document ID. It changes for every new application of a person']
  "expiring_on" varchar(100) [not null] 
  "issued_on" varchar(100) [not null] 
  "issued_in" varchar(100) [default: null] 

  "person_id" varchar(100) [not null, note: '']
  "national_id_number" varchar(100) [default: null, note: 'National Identification Number. Unique Citizen Identifier which can not be changes']
  "firstname" varchar(255) [default: null]  
  "lastname" varchar(150) [default: null]    
  "gender"  varchar(50) [not null]
  "birthdate" varchar(100) [not null] 
  "birthplace" varchar(150) [default: null] 
  "birth_country" varchar(150) [default: null]  
  "nationality" varchar(150) [not null]  
  "birth_certificate_number" varchar(100) [default: null]
  "birth_certificate_issued_on" varchar(100) [default: null]
  "birth_certificate_issued_in" varchar(100) [default: null]
  "profession" varchar(150) [default: null]
  "marital_status" varchar(100) [default: null]  
  "address" varchar(255) [default: null]  
  "other_address" varchar(255) [default: null]    
  "vehicle_usage" varchar(200) [default: null]
  "vehicle_color" varchar(200) [default: null] 
  "vehicle_manufacture_year" varchar(200) [default: null]
  "vehicle_brand" varchar(200) [default: null]
  "vehicle_model" varchar(200) [default: null]
  "vehicle_model_year" varchar(200) [default: null]
  "vehicle_license_plate_number" varchar(150) [not null]
  "type" varchar(200) [default: null]
  "state" varchar(200) [default: null]  
  "photo" varchar(255) [not null]      
  "created_at" timestamptz [default: `now()`]
  "updated_at" timestamptz [default: `now()`] 

  Indexes {  
   
  }
} 





Table "military_card" as MC {
  "id" bigserial [pk]  
  "application_id" varchar(50)  [default:null, note: 'Application ID']
  "application_date" varchar(50)  [default: null, note: 'Application date']
  "application_reason" varchar(100)  [default: null, note: ''] 
  
  "document_number" varchar(50) [default:null, note: 'Document ID. It changes for every new application of a person']
  "expiring_on" varchar(50) [default: null] 
  "issued_on" varchar(50) [default: null] 
  "issued_in" varchar(150) [default: null] 

  "driving_licence_number" varchar(50) [default: null] 
  "driving_licence_obtained_on" varchar(50) [default: null] 
  "driving_licence_expiring_on" varchar(50) [default: null] 
  "driving_licence_issued_on" varchar(50) [default: null] 
  "driving_licence_issued_in" varchar(150) [default: null] 


  "person_id" varchar(50) [not null, note: '']
  "national_id_number" varchar(50) [not null, note: 'National Identification Number. Unique Citizen Identifier which can not be changes']
  "firstname" varchar(255) [not null]  
  "lastname" varchar(150) [not null]   
  "original_name" varchar(150) [default: null]  
  "spouse_name" varchar(150) [default: null]  
  "gender"  varchar(10) [not null]
  "birthdate" varchar(50) [not null] 
  "birthplace" varchar(150) [default: null] 
  "birth_country" varchar(150) [default: null]   
  "birth_certificate_number" varchar(50) [default: null]
  "birth_certificate_issued_on" varchar(50) [default: null]
  "birth_certificate_issued_in" varchar(150) [default: null]
  "nationality_certificate_number" varchar(50) [default: null]
  "nationality_certificate_issued_on" varchar(50) [default: null] 
  "profession" varchar(150) [default: null]
  "marital_status" varchar(50) [default: null]  
  "address" varchar(255) [default: null]  
  "other_address" varchar(255) [default: null]   
  "height" int [default: null]  
  "particular_signs" varchar(255) [default: null]
  "hair_color" varchar(50) [default: null] 
  "blood_group" varchar(50) [default: null] 
  "mother_firstname" varchar(150) [default: null]
  "mother_lastname" varchar(150) [default: null]
  "father_firstname" varchar(150) [default: null]
  "father_lastname" varchar(150) [default: null] 
  "poc_firstname" varchar(150) [default: null, note: 'Name of contact person']
  "poc_lastname" varchar(150) [default: null] 
  "poc_address" varchar(255) [default: null]
  "poc_phone" varchar(50) [default: null] 
  "photo" varchar(50) [not null]     
  "created_at" timestamptz [not null, default: `now()`]
  "updated_at" timestamptz [not null, default: `now()`] 
  
  Indexes { 
  }
}  



Table "gendarme_card" as GC {
  "id" bigserial [pk]  
  "application_id" varchar(50)  [default: null, note: 'Application ID']
  "application_date" varchar(50)  [default: null, note: 'Application date']
  "application_reason" varchar(100)  [default: null, note: ''] 
  
  "document_number" varchar(50) [default: null, note: 'Document ID. It changes for every new application of a person']
  "expiring_on" varchar(50) [default: null] 
  "issued_on" varchar(50) [default: null] 
  "issued_in" varchar(150) [default: null] 

  "driving_licence_number" varchar(50) [default:null, note: '']
  "driving_licence_obtained_on" varchar(50) [default: null] 
  "driving_licence_expiring_on" varchar(50) [default: null] 
  "driving_licence_issued_on" varchar(50) [default: null] 
  "driving_licence_issued_in" varchar(150) [default: null] 


  "person_id" varchar(50) [not null, note: '']
  "national_id_number" varchar(50) [not null, note: 'National Identification Number. Unique Citizen Identifier which can not be changes']
  "service_number" varchar(50) [default: null, note: 'Service numner']
  "firstname" varchar(255) [not null]  
  "lastname" varchar(150) [not null]   
  "original_name" varchar(150) [default: null]  
  "spouse_name" varchar(150) [default: null]  
  "gender"  varchar(10) [not null]
  "birthdate" varchar(50) [not null] 
  "birthplace" varchar(150) [default: null] 
  "birth_country" varchar(150) [default: null]   
  "birth_certificate_number" varchar(50) [default: null]
  "birth_certificate_issued_on" varchar(50) [default: null]
  "birth_certificate_issued_in" varchar(150) [default: null]
  "nationality_certificate_number" varchar(50) [default: null]
  "nationality_certificate_issued_on" varchar(50) [default: null] 
  "profession" varchar(150) [default: null]
  "marital_status" varchar(50) [default: null]  
  "address" varchar(255) [default: null]  
  "other_address" varchar(255) [default: null]   
  "height" int [default: null]  
  "particular_signs" varchar(255) [default: null]
  "hair_color" varchar(50) [default: null] 
  "blood_group" varchar(50) [default: null] 
  "mother_firstname" varchar(150) [default: null]
  "mother_lastname" varchar(150) [default: null]
  "father_firstname" varchar(150) [default: null]
  "father_lastname" varchar(150) [default: null] 
  "poc_firstname" varchar(150) [default: null, note: 'Name of contact person']
  "poc_lastname" varchar(150) [default: null] 
  "poc_address" varchar(255) [default: null]
  "poc_phone" varchar(50) [default: null] 
  "photo" varchar(50) [not null]     
  "created_at" timestamptz [not null, default: `now()`]
  "updated_at" timestamptz [not null, default: `now()`] 
  
  Indexes {
    document_number
    national_id_number
  }
}  



Table "police_card" as PC {
  "id" bigserial [pk]  
  "application_id" varchar(50)  [default:null, note: 'Application ID']
  "application_date" varchar(50)  [default: null, note: 'Application date']
  "application_reason" varchar(100)  [default: null, note: ''] 
  
  "document_number" varchar(50) [not null, note: 'Document ID. It changes for every new application of a person']
  "expiring_on" varchar(50) [not null] 
  "issued_on" varchar(50) [not null] 
  "issued_in" varchar(150) [default: null] 

  "driving_licence_number" varchar(50) [default: null, note: '']
  "driving_licence_obtained_on" varchar(50) [default: null] 
  "driving_licence_expiring_on" varchar(50) [default: null] 
  "driving_licence_issued_on" varchar(50) [default: null] 
  "driving_licence_issued_in" varchar(150) [default: null] 


  "person_id" varchar(50) [not null, note: '']
  "national_id_number" varchar(50) [not null, note: 'National Identification Number. Unique Citizen Identifier which can not be changes']
  "firstname" varchar(255) [not null]  
  "lastname" varchar(150) [not null]   
  "original_name" varchar(150) [default: null]  
  "spouse_name" varchar(150) [default: null]  
  "gender"  varchar(10) [not null]
  "birthdate" varchar(50) [not null] 
  "birthplace" varchar(150) [default: null] 
  "birth_country" varchar(150) [default: null]   
  "birth_certificate_number" varchar(50) [default: null]
  "birth_certificate_issued_on" varchar(50) [default: null]
  "birth_certificate_issued_in" varchar(150) [default: null]
  "nationality_certificate_number" varchar(50) [default: null]
  "nationality_certificate_issued_on" varchar(50) [default: null] 
  "profession" varchar(150) [default: null]
  "marital_status" varchar(50) [default: null]  
  "address" varchar(255) [default: null]  
  "other_address" varchar(255) [default: null]   
  "height" int [default: null]  
  "rank" varchar(255) [default: null]
  "particular_signs" varchar(255) [default: null]
  "hair_color" varchar(50) [default: null] 
  "blood_group" varchar(50) [default: null] 
  "mother_firstname" varchar(150) [default: null]
  "mother_lastname" varchar(150) [default: null]
  "father_firstname" varchar(150) [default: null]
  "father_lastname" varchar(150) [default: null] 
  "poc_firstname" varchar(150) [default: null, note: 'Name of contact person']
  "poc_lastname" varchar(150) [default: null] 
  "poc_address" varchar(255) [default: null]
  "poc_phone" varchar(50) [default: null] 
  "photo" varchar(50) [not null]     
  "created_at" timestamptz [not null, default: `now()`]
  "updated_at" timestamptz [not null, default: `now()`] 
  
  Indexes {
    document_number
    national_id_number
  }
}  

Table api_auth {
  id bigserial [pk] 
  partner_id int [default: null,  note: "Référence à l'identifiant de partenaire"]
  username varchar [unique, not null, note: "Nom d'utilisateur (optionnel si email suffit)"]
  email varchar [unique, not null, note: "Adresse email (utilisée pour la connexion et la communication)"]
  is_email_verified bool [not null, default: false]
  hashed_password varchar [not null, note: "Mot de passe sécurisé (hashé)"]
  enabled bool [not null, default: false, note: "Compte actif ou non"]
  password_changed_at timestamptz [not null, default: '0001-01-01 00:00:00Z', note: "Date de dernière modification du mot de passe"]
  created_at timestamptz [not null, default: `now()`, note: "Date de création du compte"]
  updated_at timestamptz [not null, default: `now()`, note: "Date de dernière mise à jour du compte"]
}

Table api_auth_session {
  id uuid [pk]
  username varchar [not null, note: "Nom d'utilisateur concerné"]
  refresh_token varchar [not null, note: "Jeton de rafraîchissement pour prolonger la session"]
  user_agent varchar [not null, note: "Navigateur ou client utilisé"]
  client_ip varchar [not null, note: "Adresse IP du client"]
  is_blocked bool [not null, default: false, note: "Session bloquée ou non"]
  expires_at timestamptz [not null, note: "Date d'expiration de la session"]
  created_at timestamptz [not null, default: `now()`, note: "Date de création de la session"]
}


Table api_auth_email_check {
  id bigserial [pk]
  username varchar [ref: > api_auth.username, not null]
  email varchar [not null]
  secret_code varchar [not null]
  is_used bool [not null, default: false]
  created_at timestamptz [not null, default: `now()`]
  expired_at timestamptz [not null, default: `now() + interval '50 minutes'`]
}

Table billing_plans {
  id int [pk]
  code varchar(50) [unique, not null, note: "Code unique du plan (standard, premium...)"]
  name varchar(150) [not null, note: "Code unique du plan (standard, premium...)"]
  description text [note: "Description détaillée du plan"]
  rate_per_request numeric(10,2) [default: null, note: "Coût par requête API"]
  currency text [not null, default: 'XOF', note: "Devise utilisée (ex : XOF)"]
  monthly_request_quota integer [note: "Nombre de requêtes mensuelles autorisées"]
  auto_block_on_quota_exceed bool [default: true, note: "Blocage automatique en cas de dépassement du quota"]
}

Table partners {
  id bigserial [pk] 

  // Informations légales
  legal_name varchar(150) [not null, note: "Raison sociale de l'entité partenaire"]
  commercial_name varchar(150) [default: null, note: "Nom commercial si différent de la raison sociale"]
  registration_number varchar(150) [default: null, unique, note: "Numéro d'immatriculation (RCCM)"]
  tax_identification_number varchar(150) [default: null, unique, note: "Numéro d'identification fiscale (NIF)"]

  // Contact administratif
  admin_contact_name varchar(150) [note: "Nom du contact administratif"]
  admin_contact_email varchar(150) [note: "Email du contact administratif"]
  admin_contact_phone varchar(150) [note: "Téléphone du contact administratif"]

  // Contact technique
  tech_contact_name varchar(150) [note: "Nom du contact technique"]
  tech_contact_email varchar(150) [note: "Email du contact technique"]
  tech_contact_phone varchar(150) [note: "Téléphone du contact technique"]

  contract_signed bool [default: false, note: "Contrat signé ou non"]
  contract_signed_at timestamptz [default: null, note: "Date de signature du contrat"]
  contract_expiration timestamptz [default: null,  note: "Date d'expiration du contrat"]
  compliance_status varchar(50) [default: 'pending', note: "Statut de conformité : pending, approved, suspended, rejected, revoked"]

  // Accès API
  api_key varchar(255) [default: null, unique, note: "Clé d'accès API du partenaire"]
  api_secret text [default: null, note: "Secret API pour signature sécurisée"]
  allowed_ips text[] [note: "Liste blanche des IP autorisées"]
  authentication_mode varchar(30) [default: 'JWT', note: "Mode d'authentification : API_KEY, HMAC, JWT"]

  // État et audit
  is_active bool [not null, default: true, note: "Statut actif ou inactif"]
  activation_date timestamptz [default: null, note: "Date d’activation"]
  deactivation_date timestamptz [default: null, note: "Date de désactivation"]

  // Facturation
  billing_plan varchar(50) [default: 'standard', note: "Type de plan tarifaire appliqué"]
  billing_plan_id int [default: null, note: "Référence au plan tarifaire"]
  billing_cycle varchar(50) [not null, default: 'monthly', note: "Cycle de facturation : monthly, quarterly..."]
  payment_method varchar(50) [default: 'invoice', note: "Méthode de paiement : invoice, prepaid..."]

  alert_email_enabled bool [default: true, note: "Alertes par email activées"]
  last_alert_sent_at timestamptz [note: "Date de dernière alerte envoyée"]

  metadata jsonb [default: '{}', note: "Métadonnées personnalisées"]

  created_at timestamptz [default: `now()`, note: "Date de création"]
  updated_at timestamptz [default: `now()`, note: "Date de dernière mise à jour"]
}


Table partner_billing_plans {
  id bigserial [pk]
  partner_id int [not null, ref: > partners.id]
  billing_plan_id int [not null, ref: > billing_plans.id]

}

Table partner_access_logs {
  id bigserial [pk] 
  partner_id int [not null, note: "Référence au partenaire"]
  access_time timestamptz [default: `now()`, note: "Date et heure d'accès"]
  ip_address varchar(50) [note: "IP du client appelant"]
  user_agent text [note: "Client HTTP utilisé"]
  action varchar(50) [not null, note: "Action effectuée (LOGIN, API_CALL...)"]
  description text [default: null, note: "Description ou contexte de l'action"]
  partner_api_call_log_id int [default: null, note: "Référence à l'appel API concerné"]
}

Table partner_api_call_logs {
  id bigserial [pk] 
  partner_id int [not null, note: "Référence au partenaire"]
  access_time timestamptz [default: `now()`, note: "Horodatage de l'accès"]
  status varchar(50) [not null, note: "Statut de la requête (succès, erreur...)"]
  document_type varchar(50) [not null, note: "Type de document consulté (CNI, passeport...)"]
  document_number varchar(50) [not null, note: "Numéro de document recherché"]
  metadata json [default: '{}', note: "Métadonnées personnalisées"]
}

Table partner_change_logs {
  id bigserial [pk] 
  partner_id int [not null, note: "Référence au partenaire"]
  changed_at timestamptz [default: `now()`, note: "Date du changement"]
  changed_by varchar(150) [note: "Auteur du changement (utilisateur ou système)"]
  field_name varchar(150) [not null, note: "Champ modifié"]
  old_value varchar(150) [note: "Ancienne valeur"]
  new_value varchar(150) [note: "Nouvelle valeur"]
  change_reason text [default: null, note: "Motif du changement"]
}

Ref: api_auth.partner_id > partners.id
Ref: partners.billing_plan_id > billing_plans.id
Ref: partner_api_call_logs.partner_id > partners.id
Ref: partner_access_logs.partner_id > partners.id
Ref: partner_access_logs.partner_api_call_log_id > partner_api_call_logs.id
Ref: partner_change_logs.partner_id > partners.id
